name: 'credit_risk'
version: '1.0.0'
config-version: 2

profile: 'credit_risk'

model-paths: ["models"]
clean-targets: ["target", "dbt_packages"]

models:
  credit_risk:
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table