version: 2

sources:
  - name: bronze
    schema: bronze
    tables:
      - name: application_train
      - name: application_test
      - name: bureau
      - name: bureau_balance
      - name: previous_application
      - name: installments_payments
      - name: "POS_CASH_balance"
      - name: credit_card_balance